# Generated by Django 4.2.1 on 2023-10-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telephone_number',
        ),
    ]
